[package]
name = "pigeonnet-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
pigeonnet-core.workspace = true
pigeonnet-proto.workspace = true
pigeonnet-node.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
getrandom.workspace = true
pigeonnet-crypto.workspace = true
